@startuml
!theme cyborg-outline

<style>
    diamond {
        BackgroundColor #ccf
    }
    partition {
        FontColor green
        RoundCorner 10
    }
  arrow {
    FontColor black
    FontName arial
  }
</style>

title
    SwissgliderTheHome Adapter - Upload ConfigFile
end title

start
partition "On the Browser" {
    :Upload YAML/JSON on Admin Page;
}
partition "on adapter admin" {
:sendTo configUpload;
}
partition "on adapter" {
    :configUpload;
    partition "pre work" {
        fork
            #palegreen:stop BatteryChecker;
            fork again
            #palegreen:stop ConnectionChecker;
            fork again
            :remove all states from function and room enums;
            fork again
            :remove state.native.swissglider.theHome.store2DB
            parameter from all states;
        end fork
    }
    partition "set new config" {
        repeat
            :add all states to enums (functions/rooms) and create the enum if needed;
            :change name and store2DB on all Objects;
        repeat while (read next config state?)
    }
    partition "post work" {
        fork
            #palegreen:new init BatteryChecker;
            fork again
            #palegreen:new init ConnectionChecker;
        end fork
    }
    partition "result" {
        :return result;
    }
}
stop

@enduml