@startuml
!theme cyborg-outline

<style>
    diamond {
        BackgroundColor #ccf
    }
    partition {
        FontColor green
        RoundCorner 10
    }
  arrow {
    FontColor black
    FontName arial
  }
</style>

title
    SwissgliderTheHome Adapter - Upload SingleStateConfig
end title

start
partition "On the Browser" {
    :Enter Config to upload on Admin Page;
}
partition "on adapter admin" {
:sendTo singleStateConfigUploader;
}
partition "on adapter" {
    :singleStateConfigUpload;
    partition "pre work" {
        fork
            #palegreen:stop BatteryChecker;
            fork again
            #palegreen:stop ConnectionChecker;
            fork again
            :remove state from all function and room enum;
        end fork
    }
    partition "set new config" {
        :add state to enums (functions/rooms) and create the enum if needed;
        :change name and store2DB on Object;
    }
    partition "post work" {
        fork
            #palegreen:new init BatteryChecker;
            fork again
            #palegreen:new init ConnectionChecker;
            fork again
            #palegreen:influxDBHandlerAdapter: update all Labels;
        end fork
    }
    partition "result" {
        :return result;
    }
}
stop

@enduml